typography_spectrum: 0.12273736086351299
color:
  brandColors:
    - '#004252'
    - '#65BBD6'
    - '#A77574'
    - '#CDCCC8'
    - '#201420'
  brandStrength: 0.5898303934158111
  lightness: 0.39860854145369984
  saturation: 0.4871886311571049
  rhythmicContrast: 0.7014942032423349
github: true
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.9985995795025425
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Yuko Fukushima
  url: 'http://yukorabb.it'
  email: m@yukorabb.it
name: YukoArts
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Yuko Fukushima
content: []
description: Illustration & Digital Painting
purpose: []
