typography_spectrum: 0.9287902943324298
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.3063696934841573
  lightness: 0.033907052827998996
  saturation: 0.3919792138040066
  rhythmicContrast: 0.18829039251431823
github: true
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.9908424555324018
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Yuko Fukushima
  url: 'http://yukorabb.it'
  email: m@yukorabb.it
name: YukoArts
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: About me
    id: 8da7eef5-3df3-427a-b618-0ff6cffa1017
    type: content
favicon: null
title: Yuko Fukushima
content: []
description: Illustration & Digital Painting
purpose:
  - type: contact
    url: 'mailto:m@yukorabb.it'
    label: Contact me
